name: Sonic Blog
favicon: null
layout_spectrum: 1
typography_spectrum: 0.60018
title: Sonic CoLab
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73143886-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#067df7'
    - '#404040'
    - '#a8d2fb'
    - '#69b1f8'
  brandStrength: 0.875
  lightness: 0.5625
  saturation: 0.125
  rhythmicContrast: 1
purpose: []
