typography_spectrum: 0.60018
color:
  brandColors:
    - '#ffffff'
    - '#067df7'
    - '#404040'
    - '#a8d2fb'
    - '#69b1f8'
  brandStrength: 1
  lightness: 0.6875
  saturation: 1
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: UA-73143886-1
  facebook: null
  twitter: null
name: SONIC RECORDS
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 'SONIC : LABS'
purpose: []
